# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a2bbb1b9bb0f734e23eea16ee44259350625993064c8bffd3b0a796a72c471d2e57128471a944d90a9e35b6f5661886334c4f8709e55fdf17a26bc9b6d17ccf

test:
  secret_key_base: 4236afc74d760213e6fcba7e1d8dd16c29ffa2b298b0e767583ddbdbf5c5430c6193a930b21d7235eee4c132fef70dacce60aca7aa710c99152939a739ba31f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
